export const WordsArray = {
  ផឹក: "to drink, to swallow a liquid",
  ដី: "Earth, land",
  ចូលចិត្ត: "to like (something)",
  ក: "neck",
  មិត្ត: "friend",
  សម្រាប់: "used for, used to",
  ជា: "to be",
  ជិត: "to be close, near, almost",
  មួយ: "one",
  និង: "and",
  ដូរ: "to exchange, barter",
  នឹក: "to miss",
  គិត: "to think, to intend to",
  ការងារ: "job",
  រំលឹក: "to remind, to recall",
  ថ្មី: "new",
  ចិតសិប: "seventy",
  ប្រាំបី: "eight",
  ប្រាំពីរ: "seven",
  ថា: "to say, tell, pronounce",
  ប្រាំបួន: "nine",
  នៅលើ: "to be on",
  ពីរ: "two",
  នៅក្នុង: "to be inside",
  ទុក: "to put, to arrange",
  គួរ: "should",
  ព្រឹក: "morning",
  សែសិប: "forty",
  គូ: "pair",
  គឺ: "be, is",
  ជី: "fertilizer",
  ហាសិប: "fifty",
  ដឹក: "to transport",
  បួន: "four",
  កី: "loom",
  ផ្សិត: "mushroom, fungus",
  ឆា: "to stir-fry",
  គុក: "jail",
  សាមសិប: "thirty",
  ពុក: "father (address form)",
  ញឹក: "often, frequently",
  នៅ: "to be at",
  ខ្ញុំ: "I",
  បុក: "to collide with, to crush",
  អ្នក: "person, you",
  មួយចំនួន: "some",
  ប្រទេស: "country, nation",
  គូរ: "to draw",
  ម្ភៃ: "twenty",
  មាន: "to have, there is",
  ដប់: "ten",
  វា: "it",
  ពាក្យ: "word",
  ហុកសិប: "sixty",
  អ្វី: "what",
  ដូចជា: "just like, such as",
  ចេញ: "to leave",
  នៃ: "of",
  អាច: "to be able",
  រីករាយ: "to be happy",
  យើង: "we, us",
  នាក់: "classifier for people",
  ជួប: "to meet",
  ប្រាំ: "five",
  ពី: "from",
  បាទ: "yes (male)",
  ប្រាំមួយ: "six",
  ក្តៅ: "hot",
  ដោយ: "by, in accordance (with)",
  ឈ្មោះ: "to be named, called",
  ជួរ: "line, column",
  ផ្សេងទៀត: "other",
  ប៉ែតសិប: "eighty",
  ដែល: "who, whom, which, that, ever, used to",
  បី: "three",
  នេះ: "this",
  កៅសិប: "ninety",
  ចេះ: "to know (how to do something)",
  ដឹង: "to know (a fact)",
  លេង: "to play",
  ស្គាល់: "to know (someone, place)",
  ធ្វើការ: "to work",
  ចង់បាន: "to want (something)",
  សុទ្ធ: "pure, clean",
  ចង់: "to want (to do something)",
  ទឹកដោះគោ: "cow's milk",
  កាហ្វេ: "coffee",
  បាល់ទាត់: "soccer",
  ទឹក: "water",
  ស្ករ: "sugar",
  ពងមាន់: "chicken egg",
  ពងទា: "duck egg",
  ត្រសក់: "cucumber",
  ប៉េងប៉ោះ: "tomato",
  ការ៉ុត: "carrot",
  ជាមួយ: "with, along with",
  ម្ទេស: "chili pepper",
  ខ្ទឹមស: "garlic",
  ពោត: "corn",
  សាច់ជ្រូក: "pork",
  សាច់គោ: "beef",
  ឆ្លើយ: "to answer, reply",
  ត្រី: "fish",
  អោយ: "to give, allow",
  ទៅ: "to go, to",
  រស់នៅ: "to live (at)",
  ហែលទឹក: "to swim",
  និយាយ: "to speak, say",
  រៀន: "to learn, study",
  ជួយ: "to help, assist",
  សរសេរ: "to write",
  មកពី: "to come from",
  ដើរ: "to walk",
  អាន: "to read (aloud)",
  រត់: "to run",
  គេង: "to sleep",
  ស្តាប់: "to listen (to)",
  ធ្វើ: "to do",
  មក: "to come",
  មើល: "to look at, watch",
  ជិះ: "to ride",
  យល់: "to understand",
  បិទ: "to close, cover, turn off",
  រាំ: "to dance",
  ទិញ: "to buy",
  ពិបាក: "difficult",
  បើក: "to drive, open, turn on",
  បង្រៀន: "to teach, instruct",
  ស្អាត: "clean, nice, beautiful",
  យំ: "to cry",
  ល្អ: "good, well",
  ថោក: "cheap",
  យក: "to take, to bring",
  ស្រួល: "easy",
  ថ្លៃ: "expensive, cost",
  អាក្រក់: "bad, wicked",
  លឿន: "fast",
  យឺត: "slow, late",
  ធំ: "large",
  តូច: "small",
  ខ្ពស់: "tall",
  ត្រជាក់: "cold",
  ខុសគ្នា: "different",
  ទាប: "short",
  ធ្ងន់: "heavy",
  ប្រជុំ: "meeting, gathering",
  ដូចគ្នា: "alike, same",
  ទីតាំង: "position",
  ព្រះវិហារ: "temple",
  សាលារៀន: "school",
  សណ្ឋាគារ: "guesthouse",
  ស្រាល: "light (weight)",
  ផ្ទះ: "house",
  ហាង: "shop, store",
  ការិយាល័យ: "office",
  រដ្ឋាភិបាល: "government",
  មន្ទីរពេទ្យ: "hospital",
  ធនាគារ: "bank",
  អង្គការ: "organization",
  ក្រុមហ៊ុន: "company",
  វាំង: "Royal Palace",
  ផ្សារ: "market",
  បត់: "to turn",
  ស្តាំ: "right",
  បន្ទប់: "room",
  ក្រោយ: "next, behind, after",
  ទីនេះ: "here",
  ទីក្រុង: "city",
  ឆ្ងាយ: "far, distant",
  ឆ្វេង: "left",
  នោះ: "that, those",
  ម៉ូតូ: "motorbike",
  ឡាន: "automobile, car",
  វត្ត: "pagoda",
  ដូច្នេះ: "so, thus",
  ភូមិ: "village",
  មុខ: "face, front",
  អាទិត្យ: "week",
  ក្រោម: "below, under",
  មុនពេល: "before doing something",
  រួចហើយ: "and then",
  បើសិនជា: "if",
  បន្ទាប់មក: "afterwards, later",
  លើ: "on, above",
  ពីព្រោះ: "because (formal), since",
  ថ្ងៃ: "day, sun",
  កន្លង: "past, last",
  សម្រាក: "to relax",
  គ្រាន់តែ: "only, merely",
  រហូតដល់: "up to, until",
  ឆ្នាំ: "year",
  តែងតែ: "always, constantly",
  ខេត្ត: "province",
  ថ្ងៃនេះ: "today",
  ខែ: "month, moon",
  ក្រៅ: "outside",
  ប្រហែលជា: "maybe, approximately",
  ម្សិលមិញ: "yesterday",
  ដើម្បី: "in order to",
  ធ្វើដំណើរ: "to travel",
  រហូត: "until, up to",
  ថ្ងៃអាទិត្យ: "Sunday",
  ថ្ងៃច័ន្ទ: "Monday",
  ចំណី: "(animal) feed",
  ថ្ងៃសៅរ៍: "Saturday",
  ដំបូង: "at first",
  ស៊ី: "to eat (for an animal)",
  យាយ: "grandmother",
  ថ្ងៃសុក្រ: "Friday",
  ថ្ងៃព្រហស្បតិ៍: "Thursday",
  ដែរ: "also, too, makes gentler",
  ជនជាតិ: "nationality, citizen",
  តម្លៃ: "price, value",
  ទាំងពីរ: "both",
  ថ្ងៃអង្គារ: "Tuesday",
  ចូល: "to enter",
  ថ្ងៃពុធ: "Wednesday",
  បង្ហាញ: "to show, demonstrate",
  ណែនាំ: "to advise, guide",
  ជនបរទេស: "foreigner",
  បញ្ជី: "list, chart",
  រួច: "already, to finish",
  ពេក: "too, too much",
  បរទេស: "foreign",
  តោ: "lion",
  កៅ: "ninety (short)",
  ពិសេស: "special",
  គោ: "cow, ox",
  ប៉ា: "father, you",
  ឆ្ងាញ់: "tasty, delicious",
  ឃើញ: "to see, perceive",
  ហៅ: "to call, to order",
  ប្តី: "husband",
  មា: "uncle (younger brother)",
  ប្រពន្ធ: "wife",
  កូនប្រុស: "son",
  ឪពុក: "father (formal)",
  ស្រី: "woman, female",
  រក: "to look for, search for",
  ម្តាយ: "mother (formal)",
  ខោ: "pants",
  ពូ: "uncle (1)",
  មែន: "real, accurate",
  ប្រុស: "man, male",
  មុន: "previously, before",
  តា: "grandfather, you",
  ម៉ែ: "mother (casual)",
  គ្រួសារ: "family",
  ស្រដៀង: "similar",
  ពណ៌: "color",
  ដល់: "to, toward, up to",
  ពណ៌ខ្មៅ: "black",
  ពណ៌ស: "white",
  ជើង: "leg, foot",
  អាវ: "shirt, blouse",
  ឈាម: "blood",
  រងា: "chilly",
  ភ្លៀង: "rain",
  ខ្សែ: "string, cord, rope",
  ខ្ចី: "light (color), to borrow, unripe",
  ចុង: "end, tip",
  ទំហំ: "size, dimenstion",
  បូក: "to add, mix together",
  ចែក: "to divide, distribute",
  ប្រយ័ត្ន: "be careful",
  ចុងក្រោយ: "the last",
  ដក: "to subtract, extract",
  គុណ: "to multiply, increase",
  ផ្អែម: "sweet, pleasant",
  ក្លិន: "smell, odor",
  មកដល់: "to arrive at, come to",
  អប់: "to be fragrant, to perfume, scent",
  វាល: "large open space, field",
  សុវត្ថិភាព: "goodness, success, safety",
  មួក: "hat, cap",
  កាបូប: "wallet, bag",
  ស្បែក: "skin, leather",
  ល: "to attempt, try (clothes)",
  ចុះ: "to descend",
  កីឡា: "sports",
  ដាច់: "detached, cut off, to break apart",
  បាត់: "to be lost",
  ប្រើ: "to use",
  ផ្ទាល់ខ្លួន: "private, personal",
  ខ្លួន: "oneself, soul",
  ផ្ទាល់: "individual",
  ចុងភៅ: "chef",
  ប្រភេទ: "category, kind",
  ទាំងអស់: "all",
  ភាសា: "language",
  កន្លែង: "place, location",
  កើត: "to be born, create, east",
  លួច: "to steal, be sneaky",
  ឡើង: "to go up, ascend",
  មូលដ្ឋាន: "base, foundation",
  រៀបរាប់: "to describe, narrate",
  កើតឡើង: "to occur",
  គួរតែ: "ought to, should",
  ក្មេង: "young, child",
  ចោរ: "theif, robber",
  គ្មាន: "without",
  រាយការណ៍: "to report",
  ក្រៅពី: "aside, besides",
  សូម: "please",
  ប៉ូលិស: "police",
  ខ្មែរ: "Khmer",
  លុយ: "money",
  យូរ: "long time, late",
  ការ: "to marry",
  ពេទ្យ: "doctor, physician",
  រូបថត: "photograph, picture",
  អង់គ្លេស: "English",
  ឥឡូវ: "now",
  ពេល: "time, moment",
  ចិន: "Chinese",
  ទីពីរ: "second",
  ទូក: "boat",
  ទីមួយ: "first",
  ទាំង: "entirely, while, together",
  ខាង: "side",
  ទាក់ទង: "to contact, be in touch",
  នាយ: "boss",
  និស្សិត: "student (college or university)",
  អាយុ: "years old",
  ទង: "flowers (counter), stem, source",
  ពន្យារ: "to prolong, extend, procrastinate",
  ទូត: "diplomat, representative",
  ចាន: "dish, plate (counter)",
  ខ្លាំង: "strong",
  ហួស: "beyond, to exceed",
  ស្ថានទូត: "embassy",
  ធ្លាក់: "to fall",
  កំណត់: "appointment, schedule",
  ឆ្លង: "to infect, pick up, move across",
  ចាយ: "to spend",
  លា: "say goodbye to",
  ស្រុក: "district",
  លិខិត: "document, certificate",
  បាងកក: "Bangkok",
  ថៃ: "Thai",
  តាម: "to follow, to go along with",
  ស្លាប់: "to die",
  ដែន: "territory, region",
  ភ្នំពេញ: "Phnom Penh",
  ធ្លាប់: "denotes completition of activity at some point",
  ស្ថាន: "institution, station, bureau",
  ទាក់: "to snare, capture, seduce",
  ដើម: "stick-like objects (counter - trees, pencils), trunk (tree)",
  ដើមឈើ: "tree",
  ឈើ: "wood",
  ទៀត: "again, more",
  រាំង: "to let up (rain), lock, block",
  បន្តិច: "a little bit (formal)",
  ទ: "drain (pipe), gutter",
  ភ្លេច: "to forget",
  ធាតុ: "nature, temperament",
  អាកាស: "air, atmosphere",
  ព្យុះ: "anger, storm",
  ខ្យល់: "wind",
  តិច: "a little",
  តិចតួច: "a little bit",
  ចេក: "banana",
  ខ្នុរ: "jackfruit",
  ក្រូច: "citrus fruit",
  ទៀប: "custard apple, close to",
  គូលែន: "lychee",
  ដូង: "coconut",
  ទុរេន: "durian",
  បាយ: "cooked rice, meal",
  ឈូក: "lotus",
  ល្ហុង: "papaya",
  ស្រូវ: "rice paddy (prior to being husked)",
  ម្នាស់: "pineapple",
  ទំពាំងបាយជូរ: "grape",
  ស៊ុប: "soup (English)",
  ម៉ាស៊ីន: "machine",
  សារី: "pear",
  ដប: "bottle, pitcher (counter)",
  គីឡូ: "kilo",
  សាច់: "flesh, meat",
  កញ្ចប់: "pack, parcel (counter)",
  រដូវ: "season",
  ផ្លែ: "fruit (grouping)",
  ឡូ: "dozen (counter)",
  ដុំ: "piece, pile, block (counter)",
  លក់: "to sell",
  ទឹកក្រូច: "orange juice",
  រលួយ: "rotten, decayed",
  សម្ល: "soup (Khmer)",
  ធុង: "barrel (counter)",
  ចំហៀង: "half (counter)",
  សាប: "weak, bland",
  សម: "fork",
  កាំបិត: "knife",
  អាហារ: "food, food products",
  ល្ងាច: "evening",
  មី: "egg noodles",
  នំ: "pastry, cake",
  បំពង: "to deep fry",
  គ្រាប់: "seed, pill (counter)",
  ការី: "curry",
  ខ្ញី: "ginger",
  មឹក: "squid",
  បង្គា: "shrimp",
  កំពង់ធំ: "Kompong Thom",
  ស្វាយចន្ទី: "cashew",
  កំពង់: "port, river town",
  អំបិល: "salt",
  ព្រម: "to agree with",
  ម្រេច: "black pepper",
  ម៉ោង: "hour",
  ឈប់: "stop",
  រៀល: "riel",
  គ្រូ: "teacher, expert",
  ប៉ុន្មាន: "how many",
  អក្សរ: "letter, alphabet",
  យល់ថា: "to think, understand that",
  ជឿ: "to believe (in), buy on credit",
  ជូន: "to escort, give someone a ride, to present",
  ព្រួយ: "to worry, be anxious (a little bit)",
  រឿង: "story, subject",
  សោ: "lock",
  មេ: "leader",
  បោក: "to wash",
  រ៉ែ: "mineral",
  បែរ: "to move, change direction",
  ទួលគោក: "Toul Kourk",
  បើ: "if (casual)",
  ទួល: "hill, mound",
  រើ: "to move",
  ដោយសារ: "by means of",
  គេ: "they (casual)",
  ឆៅ: "raw",
  លោក: "monk, man",
  គោក: "land (dry), ground",
  ដេរ: "to sew",
  ដៅ: "to mark",
  ច្បាស់: "clear, accurate",
  ត្រូវ: "must, have to",
  តារាង: "table, chart",
  អង្ករ: "uncooked rice",
  ស្រែ: "rural",
  ទឹកកក: "ice",
  រសជាតិ: "flavor",
  ខ្លះ: "some, somewhat",
  ម៉េច: "why... (casual)",
  ពួក: "group",
  ហេតុអ្វី: "why? what reason?",
  ច្រើន: "many",
  ចាប់: "to begin, painful",
  ពូកែ: "clever",
  វិទ្យា: "knowledge",
  វិទ្យាល័យ: "college",
  ចាំ: "to wait, remember",
  យប់: "night",
  ប៉ុណ្ណោះ: "only",
  គ្រប់គ្រាន់: "enough",
  រសៀល: "afternoon",
  ហ្នឹង: "this, there",
  ល្មម: "sufficient",
  ចិញ្ចឹម: "to support",
  ខ្វះ: "to lack",
  វិនាទី: "second (time)",
  ប្រាក់ខែ: "salary",
  នាទី: "minute",
  ហៅថា: "to be called",
  ហេតុ: "reason",
  ប្រាក់: "money, silver",
  ចំការ: "farm",
  ទម្លាក់: "to drop",
  ឃុំ: "town",
  សម្លាប់: "to kill",
  គ្រាប់បែក: "bomb",
  ប្រជាជន: "the people",
  ចាស់: "old",
  មនុស្ស: "people",
  ល្បី: "popular",
  អធ្រាត្រ: "midnight",
  ជីវិត: "life",
  ជាដើម: "for example",
  ផ្សេងៗ: "various",
  ជំងឺ: "disease",
  ទំនិញ: "merchandise",
  ប្រគល់: "to hand over",
  គ្រប់: "every",
  អ្វីខ្លះ: "something (plural)",
  សៀវភៅ: "book",
  ផ្លែឈើ: "fruit",
  ឆ្លៀត: "to take advantage",
  បន្លែ: "vegetable",
  អារម្មណ៍: "feeling",
  កាលពី: "on (a certain date)",
  លែង: "to release",
  ទ្វារ: "door",
  មិញ: "very recent",
  ត្រឡប់: "to return, go back",
  ដេក: "to lie down, nap",
  ត្រៀម: "to get ready",
  ស្ថានភាព: "situation",
  ឡែក: "isolated",
  ពិនិត្យ: "to inspect",
  បារម្ភ: "anxiety, uneasiness",
  ខឹង: "to be angry (at)",
  ដឹកនាំ: "to lead",
  ភាគរយ: "percent",
  បាត់បង់: "to lose",
  ជួល: "to hire, employ, rent",
  បញ្ហា: "problem",
  ថៅកែ: "businessman, capitalist",
  កម្មករ: "worker, laborer",
  ហោះ: "to fly (a plane)",
  បារ: "bar",
  ចេញពី: "to leave from",
  សោះ: "(in negative clauses) at all",
  ដំណឹង: "information",
  អនុញ្ញាត: "to allow by law, to permit",
  ប្រធាន: "president",
  ព្រួយបារម្ភ: "to be worried (very)",
  យន្តហោះ: "airplane",
  ស្ទះ: "obstruction, block",
  យន្ត: "mechanism, machine",
  បុគ្គលិក: "employee",
  ប្រេង: "oil",
  ពាក់: "to wear (anything besides pants or shirts)",
  ហេតុអ្វីបានជា: "why... (formal)",
  សក់: "hair",
  ស្រស់: "pretty, attractive",
  សេវា: "service",
  ភ្នែក: "eyes",
  ម្ខាង: "at one side",
  រុញ: "to push (forward)",
  សាំង: "gasoline",
  គំនូរ: "drawing, sketch",
  ផ្អើល: "to panic",
  ចោល: "away, off",
  យាម: "to guard, patrol",
  រង្វាន់: "reward, prize",
  ឆែក: "to check",
  គាំង: "to be stuck, jammed",
  កាត់: "to cut, slice",
  ក្បាល: "animals (counter)",
  សួន: "park",
  ច្បារ: "garden",
  នៅតែ: "to be left, remain",
  ម្ចាស់ផ្ទះ: "landlord",
  ម្ចាស់: "boss, owner",
  ស្រឡាញ់: "to love",
  ភ្ញាក់ផ្អើល: "surprised",
  ភ្ញាក់: "to wake up, appear, arise",
  ខ្លាច: "to fear",
  ឈឺ: "sick",
  កម្លាំង: "power, strength",
  ភ័យ: "scared",
};
